[project]
name = "signing-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyhanko-beid-plugin>=0.2.0",
    "pyhanko[image-support,opentype]>=0.29.1",
]
